#!/bin/sh

set -e

. ./terraform.conf


lb config noauto \
    --apt-recommends false \
    --apt-indices false \
    --apt-source-archives false \
    --architectures "$ARCH" \
    --archive-areas 'main contrib non-free' \
    --backports true \
    --security true \
    --updates true \
    --source false \
    --checksums sha512 \
    --clean \
    --debian-installer live \
    --debian-installer-distribution "$BASECODENAME" \
    --debian-installer-gui true \
    --debootstrap-options "--include=apt-transport-tor,apt-transport-https,ca-certificates,openssl" \
    --distribution "$BASECODENAME" \
    --initramfs live-boot \
    --iso-application "$NAME" \
    --iso-volume "$NAME" \
    --linux-packages "linux-image linux-headers" \
    --bootappend-live "boot=live config splash" \
    --memtest memtest86+ \
    --mirror-bootstrap "$MIRROR_URL" \
    "${@}"

# replace channel and suite
sed -i "s/@CHANNEL/$CHANNEL/" config/archives/*.list*
sed -i "s/@BASECODENAME/$BASECODENAME/" config/archives/*.list*
